### ISSUE TITLE
Auto id in PostgreSQL

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#1]
mysql has `insertId` as in for getting the last inserted id. But there is no such thing is pg, some suggest using `RETURNING` such as `INSERT INTO table (col) VALUES (val) RETURNING id` (See http://stackoverflow.com/a/2944481/3212365). 
In that case the query builder needs to know the name of the ID field. May be adding `getIdField():String` to `TableInfo` is ok.

And there seems no way to omit a field. Say the table schema is:
- `id:Int` (Auto increment)
- `foo:String`

and currently `db.table.insertOne({foo:'mystring'})` is translated to something like
`INSERT INTO table (foo, id) VALUES ('mystring', NULL)`. And this mostly results in a null exception in the db.

**Comment by kevinresol** [comment]
@andyli I just want to check if this is resolved by your postgres contribution?

**Comment by andyli** [comment]
Right. The `PostgreSqlFormatter` automatically insert a `RETURNING` when inserting into a table with auto-inc primary key.

https://github.com/haxetink/tink_sql/blob/cc9d2bd78d373ab32aba56ff97c586f0d29cb58a/src/tink/sql/format/PostgreSqlFormatter.hx#L122-L127

`PostgreSqlFormatter` adds `DEFAULT` (instead of `null`) as the value for auto-inc columns.

https://github.com/haxetink/tink_sql/blob/cc9d2bd78d373ab32aba56ff97c586f0d29cb58a/src/tink/sql/format/PostgreSqlFormatter.hx#L135
