### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by postite** [haxetink/tink_sql#80]
hello . 
is tink_sql working with sqlite ?
seems like there is an implementation but not working ...

     tink_sql/src/tink/sql/drivers/sys/Sqlite.hx

**Comment by benmerckx** [comment]
I tried reviving the Std driver to see about setting up SqLite. As far as I can tell the `ResultSet` does not allow us to get columns from each table if they have the same name, that is kind of a show stopper..

**Comment by back2dos** [comment]
Perhaps we could alias every column before the query?

**Comment by sonygod** [comment]
anynews about this? 

@back2dos

**Comment by benmerckx** [comment]
There's some progress here: #82. Sqlite passes tests on neko and php except for schema upgrades (which will either not be supported or require a different approach). Nodejs lacks an implementation since doing that properly would need a few changes to how statements are generated. I plan to look into it but there's no timeline for that.

**Comment by sonygod** [comment]
maybe you can add HashLink target for test  at first .

Sqlite passes tests on neko and php and Hashlink and hxcpp,

**Comment by benmerckx** [comment]
Closed with #91

**Comment by postite** [comment]
cool ! thx @benmerckx
